Repository DEFRA/sroc-tcm-admin, pull requests merged in 2021-11, with the labels that each got.

#480 Update README
  README.md
Labels: documentation

#481 Update sonar-project.properties
  sonar-project.properties
Labels: housekeeping

#482 Remove hotfix/ folder
  hotfix/20190314-remove_cfd_transactions.txt
Labels: documentation

#483 Remove features/ & script/ folders
  config/cucumber.yml
  features/step_definitions/.gitkeep
  features/support/env.rb
  script/cucumber
Labels: housekeeping

#484 Enable view tracking in coverband
  config/coverband.rb
Labels: housekeeping

#485 Migrate & expand Trans.FilePresenter minitests
  spec/factories/regime.rb
  spec/factories/transaction_detail.rb
  spec/factories/transaction_file.rb
  spec/lib/transaction_file_exporter_spec.rb
  spec/lib/transaction_group_filters_spec.rb
  spec/presenters/cfd_transaction_file_presenter_spec.rb
  spec/presenters/cfd_transactions_detail_presenter_spec.rb
  spec/presenters/pas_transaction_file_presenter_spec.rb
  spec/presenters/transaction_detail_presenter_spec.rb
  spec/presenters/transaction_file_presenter_spec.rb
  spec/presenters/wml_transaction_file_presenter_spec.rb
  spec/services/export_transaction_data_service_spec.rb
  test/presenters/cfd_transaction_file_presenter_test.rb
  test/presenters/pas_transaction_file_presenter_test.rb
  test/presenters/wml_transaction_file_presenter_test.rb
Labels: housekeeping

#488 Add spec for TransactionHeaderPresenter
  app/presenters/transaction_header_presenter.rb
  spec/factories/transaction_header.rb
  spec/presenters/transaction_header_presenter_spec.rb
Labels: housekeeping

#489 Add spec for TransactionCsvPresenter
  spec/presenters/transaction_csv_presenter_spec.rb
Labels: housekeeping

#497 Fix sort order defect
  app/services/query/sort_transactions.rb
Labels: bug

#490 Add specs for RetrospectiveFilePresenters
  spec/presenters/cfd_retrospective_file_presenter_spec.rb
  spec/presenters/pas_retrospective_file_presenter_spec.rb
Labels: housekeeping

#498 Add spec for PermitCategoryPresenter
  spec/presenters/permit_category_presenter_spec.rb
Labels: housekeeping

#491 Add spec for DataExportController
  app/controllers/data_export_controller.rb
  app/views/data_export/_export_data_file.html.erb
  config/routes.rb
  db/migrate/20211108161905_remove_can_generate_export_from_system_config.rb
  db/schema.rb
  spec/requests/data_export_spec.rb
Labels: housekeeping
